version: "3.9" # optional since v1.27.0
services:
    app:
        build:
            args:
                user: dev
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        working_dir: /var/www
        environment:
            - CHOKIDAR_USEPOLLING=${CHOKIDAR_USEPOLLING:-false}
        restart: unless-stopped
        ports:
            - 8080:8080
            - 4173:4173
        volumes:
            - .:/var/www
            - node_modules:/var/www/node_modules
        command: npm run dev

volumes:
    node_modules:
